// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAL.DataModel;

#nullable disable

namespace PAL.DataModel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230802124834_UpdatedWithCompleteDACSlotData")]
    partial class UpdatedWithCompleteDACSlotData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAL.DataModel.DACReservation", b =>
                {
                    b.Property<int>("DACReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DACReservationId"));

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DACSlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("DateTime2(7)");

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("DateTime2(7)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DACReservationId");

                    b.ToTable("DACReserveINV", (string)null);
                });

            modelBuilder.Entity("PAL.DataModel.DACSlot", b =>
                {
                    b.Property<int>("DACSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DACSlotId"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<int?>("DACReservationId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("Tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DACSlotId");

                    b.ToTable("SlotsINV", (string)null);

                    b.HasData(
                        new
                        {
                            DACSlotId = 1,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 2,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 3,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 4,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 5,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 6,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 7,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 8,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 9,
                            CampusId = 1,
                            Status = (byte)0
                        },
                        new
                        {
                            DACSlotId = 10,
                            CampusId = 1,
                            Status = (byte)0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
